### ISSUE TITLE
How to generate CAM for fine-tuned model and custom data set?

### ISSUE THREAD

**Issue by panovr** [metalbubble/CAM#11]
I use Caffe to fine-tune VGG-16 on a new data set. After fine-tuning, I get the fine-tuned model. So I want to ask that how to generate CAM for this fine-tuned model and custom data set?

**Comment by aicentral** [comment]
It would be a good idea to see how it is generated in this file https://github.com/metalbubble/CAM/blob/master/ILSVRC_generate_heatmap.m

**Comment by panovr** [comment]
@aicentral Thanks!
