### ISSUE TITLE
Undefined function 'loadHeatMap'

### ISSUE THREAD

**Issue by Eniac-Xie** [metalbubble/CAM#12]
Hi, when I run ILSVRC_evaluate_bbox.m to evaluate the bbox, I get the error as follow:
"Undefined function 'loadHeatMap' for input arguments of type 'char'."

The function "loadHeatMap"  used in ILSVRC_evaluate_bbox.m (line 73) is undefined. Would you like to update this script? Thank you!

**Comment by metalbubble** [comment]
It is just a wraper like the follows. ILSVRC_evaluate_bbox only provides the skeleton, you need to fill your own subprocess.

function [heatMapSet, value_category, IDX_category] = loadHeatMap( curMatFile)
 %LOADHEATMAP Summary of this function goes here
 %   Detailed explanation goes here
 load(curMatFile);
 heatMapSet = 0;

 end
