### ISSUE TITLE
Maybe a mistake in mergeTenCrop.m

### ISSUE THREAD

**Issue by mumuhe** [metalbubble/CAM#14]
Thanks for your providing of the source code, which helps me a lot.

I found a mistake in mergeTenCrop.m.

In line 25, 26

 alignImgSet(i:i+cropSize-1, j:j+cropSize-1,:,curr) = curCrop1;
 alignImgSet(i:i+cropSize-1, j:j+cropSize-1,:, curr+5) = curCrop2;

They maybe modified into 

 alignImgSet(j:j+cropSize-1, i:i+cropSize-1,:,curr) = curCrop1;
 alignImgSet(j:j+cropSize-1, i:i+cropSize-1,:, curr+5) = curCrop2;

You can check it whether it is right.

**Comment by metalbubble** [comment]
Thanks. Fixed.
