### ISSUE TITLE
Other models like VGGNet for CAM?

### ISSUE THREAD

**Issue by panovr** [metalbubble/CAM#15]
Current repository includes the train_val file and solver of the GoogleCAM, have you tried other models like VGGNet or ResNet for CAM?

**Comment by panovr** [comment]
I just see the VGGNet deploy file :+1:

**Comment by metalbubble** [comment]
you could directly use the resnet to generate the heatmap, as it already uses the global average pooling at the end.

**Comment by panovr** [comment]
Thanks!
