### ISSUE TITLE
What is name of upsampling technique you used in this code??

### ISSUE THREAD

**Issue by ckdghk77** [metalbubble/CAM#16]
Hello, I read the code and paper "Learning Deep Features for Discriminative Localization". Now I'm trying to apply this method to a smaller class label case (only 2). Everything was okay before the up-sampling part. However, In the up-sampling part (Maybe mergeTencrops.m are doing this) I can't get the technique you used, so now I'm trying to search in google or find some paper about it if you tell some information about the technique. 

In sum, can you tell me about the name of technique you used in mergeTencrops ??

Thank you for reading.

**Comment by metalbubble** [comment]
bilinear subsampling.
