### ISSUE TITLE
How to get the coords from heatmap?

### ISSUE THREAD

**Issue by yanxp** [metalbubble/CAM#17]
Hello,how is the heatmap_6.txt generated?

**Comment by metalbubble** [comment]
https://github.com/metalbubble/CAM/blob/master/generate_bbox.m

**Comment by yanxp** [comment]
@metalbubble  I mean how to generate to coords. In the generate_bbox.m ,there is already heatmap_6.txt existed. Thank you.

**Comment by metalbubble** [comment]
see line 20 of the script.
