### ISSUE TITLE
problem with the trained model

### ISSUE THREAD

**Issue by asnadyvt** [metalbubble/CAM#2]
The trained models provided at http://cnnlocalization.csail.mit.edu/demoCAM/models/imagenet_googleletCAM_train_iter_120000.caffemodel
which is downloaded using the download.sh script is too small (3.75MB) , also it gives error while running the demo.m with online=1
` Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: models/imagenet_googleletCAM_train_iter_120000.caffemodel`

**Comment by metalbubble** [comment]
Thanks for pointing it out @asnadyvt ! I updated a new version of caffemodel. Can you try it again?

**Comment by asnadyvt** [comment]
it looks OK now , Many thanks
