### ISSUE TITLE
Applying threshold on negative weight values or not?

### ISSUE THREAD

**Issue by ozancaglayan** [metalbubble/CAM#22]
Hello,

I saw that in Places365 CAM [code](https://github.com/CSAILVision/places365/blob/master/run_placesCNN_unified.py), a thresholding is applied over the softmax layer weights while in this repository and in the original paper, there's no mention about this trick.

Is there an explanation for this?

Thanks!

**Comment by metalbubble** [comment]
Thresholding the softmax weight will make the heatmap highlight all the positively contributed areas. Also previously I found the rendering code for the heatmap didn't handle the negative feature map very well. 

But it is interesting to explore the negative image region for the prediction, for example, a sofa region would have a negative effect on predicting beach category.

**Comment by neouyghur** [comment]
Hi, I also find negative weights in my implementation. I also used the threshold for avoiding negative weights. However, I am curious what have you done in your experiments. Could you explain it in more detail? Thanks.
