### ISSUE TITLE
minor bug in pytorch code?

### ISSUE THREAD

**Issue by isht7** [metalbubble/CAM#25]
I am using [this](https://github.com/metalbubble/CAM/blob/master/pytorch_CAM.py) script in pytorch available in your repository. 
Currently, [this](https://github.com/metalbubble/CAM/blob/master/pytorch_CAM.py#L47) line is 
`cam = weight_softmax[class_idx].dot(feature_conv.reshape((nc, h*w)))`
But I think it should be,
`cam = weight_softmax[idx].dot(feature_conv.reshape((nc, h*w)))`

class_idx should be replaced by idx, becuase class_idx is a list, idx is a integer.

**Comment by panjunwen** [comment]
I agree.

**Comment by metalbubble** [comment]
Thanks. Fixed.

**Comment by isht7** [comment]
Thanks.
