### ISSUE TITLE
Pretrained VGG16CAM Model

### ISSUE THREAD

**Issue by soon-will** [metalbubble/CAM#32]
Thanks for your effort. Could you please share the pretrained vgg16CAM model?

Thanks.

**Comment by liuzh-buaa** [comment]
I have the same question as you.

I tried to convert caffemodel to torchmodel accroding to prototxt and .caffemodel, but the accuracy is much lower than it should be. Would you share the pretrained vgg16CAM model with me? Or Is there anything I should pay special attention to?

Thanks.

**Comment by soon-will** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，你的邮件已收到,我会尽快给你回复。

**Comment by liuzh-buaa** [comment]
你好！邮件已经收到！祝好~liuzh
