### ISSUE TITLE
Doubt about using pytorch_CAM.py 

### ISSUE THREAD

**Issue by Rahul-Venugopal** [metalbubble/CAM#33]
Hi ,
Actually I am new to this field and I am now checking out the possibility of using CAM for Weakly Supervised Object Localization. 

As far as I understood , If I have trained a classifier (lets say to classify 3 objects) with network architectures such as resnet, densenet, or other squeezenet that use global average pooling at the end . I can apply your pytorch_CAM.py in the repository to generate heat_maps for those 3 classes.

It would be great , if anyone can correct me if I am wrong.

Thanks
rahul

**Comment by metalbubble** [comment]
Yes.
