### ISSUE TITLE
In the 'online' mode, matlab crashed when running caffe.Net(model, weight, 'test')

### ISSUE THREAD

**Issue by funnyzhou** [metalbubble/CAM#5]
The error is :
Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: CAM/models/vgg16CAM_train_iter_90000.caffemodel
*** Check failure stack trace: ***

I think it might be the problem of the version of caffe...

**Comment by metalbubble** [comment]
can you git clone the latest version of caffe and try? thanks.
