### ISSUE TITLE
How can I run use the dt_box and run the generate_bbox.m？

### ISSUE THREAD

**Issue by tingtinglu** [metalbubble/CAM#6]
I am not familiar to C++. I want to run your code `generate_bbox.m`, but when it runs to the line 
```system(['bboxgenerator/./dt_box ' curHeatMapFile ' ' curParaThreshold ' ' curBBoxFile]);```
some errors occur.  e.g., the generate_bbox cannot be used. 

I have some questions:
- where can i obtain generate_bbox, whether is it a .dll file or some other files？
- second: how can i compile the dt_box? in fact, i have established a new project, and add the files dt.c, dt.h,dt_box.cpp., and obtained a dt_box.exe, but it cannot be used.
Can you give me some helps? thanks so much!

**Comment by metalbubble** [comment]
dt_box is compiled program in linux. The source code is also provided at https://github.com/metalbubble/CAM/blob/master/bboxgenerator/dt_box.cpp

If you use windows, probably you need to adapt the code into windows version. I am not so sure how to do it exactly as I don't use windows.

**Comment by tingtinglu** [comment]
thanks so much for your response! I have compiled in linux and it can be used now!
