### ISSUE TITLE
a queston about the results on the classification

### ISSUE THREAD

**Issue by tingtinglu** [metalbubble/CAM#7]
I have a question about the results on the classification in the paper: 

>For classification, why do you compare your GAP network with the NIN? NIN also has the GAP layer, then what can be included when the GAP network performs better than NIN? 

I am really a little confused about this, so could you be so kind to give me some explanations? Thanks!

**Comment by metalbubble** [comment]
we just reuse the original GAP layer of the NIN for localization.
