### ISSUE TITLE
Why average pooling instead of global average pooling.

### ISSUE THREAD

**Issue by mrgloom** [metalbubble/CAM#8]
Why do you use average pooling instead of global average pooling like in paper?

~~~
layers {
  name: "CAM_pool"
  type: POOLING
  bottom: "CAM_conv"
  top: "CAM_pool"
  pooling_param {
    pool: AVE
    kernel_size: 14
    stride: 14
  }
}
~~~

**Comment by metalbubble** [comment]
The final conv feature size is 14x14, so the AVE of 14x14 is equivalent to global average pooling. I am not sure if there is a layer in caffe called global average pooling.
