### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by moh3th1** [metalbubble/CAM#9]
How to fine tune your model? 
I don't have sufficient data to retrain your model from scratch.I want to fine tune your model on my data which has only two classes ?

**Comment by metalbubble** [comment]
I included the train_val file and solver of the GoogleCAM. You just follow the standard fine-tuning procedure to finetune the googleCAM model.

If you are not familiar with fine-tuning in caffe, you could just google fine-tune in caffe, or take this page as example: http://caffe.berkeleyvision.org/gathered/examples/finetune_flickr_style.html
